baseURL = 'https://philipmallis.gr/'
languageCode = 'el'
title = 'Î¦Î¯Î»Î¹Ï€Ï€Î¿Ï‚ ÎœÎ¬Î»Î»Î·Ï‚'
theme = 'PaperMod'
copyright = '[Philip Mallis](https://philipmallis.com)'

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"

author = "Me"
DateFormat = "2 January 2006"
disableThemeToggle = "false"

ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true

[homeInfoParams]
Title = "Hi there ğŸ‘‹"
Content = "Welcome to my blog"

[[socialIcons]]
name = "x"
url = "https://x.com/"

[[socialIcons]]
name = "stackoverflow"
url = "https://stackoverflow.com"

[[socialIcons]]
name = "github"
url = "https://github.com/"

[[menu.main]]
identifier = "categories"
name = "ÎºÎ±Ï„Î·Î³Î¿ÏÎ¯ÎµÏ‚"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "ÎµÏ„Î¹ÎºÎ­Ï„ÎµÏ‚"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "website"
name = "Î¹ÏƒÏ„ÏŒÏ„Î¿Ï€Î¿Ï‚"
url = "https://philipmallis.com"
weight = 30
